-- MySQL Script generated by MySQL Workbench
-- Mon Nov 15 01:21:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EzHRM
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EzHRM` ;

-- -----------------------------------------------------
-- Schema EzHRM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EzHRM` DEFAULT CHARACTER SET utf8 ;
USE `EzHRM` ;

-- -----------------------------------------------------
-- Table `EzHRM`.`ACCESSTOKENS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`ACCESSTOKENS` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`ACCESSTOKENS` (
  `Token` VARCHAR(32) NOT NULL,
  `Bitmask` INT NOT NULL,
  `NhanVienID` VARCHAR(10) NULL,
  `Account` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Token`),
  CONSTRAINT `FK_ACCESSTOKENS_NHANVIENID_ID`
    FOREIGN KEY (`NhanVienID`)
    REFERENCES `EzHRM`.`NHANVIEN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ACCESSTOKENS_ACCOUNT_TAIKHOAN`
    FOREIGN KEY (`Account`)
    REFERENCES `EzHRM`.`TAIKHOAN` (`TaiKhoan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `ID_idx` ON `EzHRM`.`ACCESSTOKENS` (`NhanVienID` ASC) VISIBLE;

CREATE INDEX `FK_ACCESSTOKENS_ACCOUNT_TAIKHOAN_idx` ON `EzHRM`.`ACCESSTOKENS` (`Account` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `EzHRM`.`BAOCAOCHAMCONG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`BAOCAOCHAMCONG` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`BAOCAOCHAMCONG` (
  `NgayBaoCao` DATE NOT NULL,
  `SoNVDenSom` INT NOT NULL,
  `SoNVDenDungGio` INT NOT NULL,
  `SoNVDenTre` INT NOT NULL,
  `SoNVTanLamSom` INT NOT NULL,
  `SoNVTanLamDungGio` INT NOT NULL,
  `SoNVLamThemGio` INT NOT NULL,
  PRIMARY KEY (`NgayBaoCao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EzHRM`.`BAOCAONHANSU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`BAOCAONHANSU` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`BAOCAONHANSU` (
  `Thang` TINYINT NOT NULL,
  `Nam` SMALLINT NOT NULL,
  `SoNhanVienMoi` INT NOT NULL,
  `SoNhanVienThoiViec` INT NOT NULL,
  PRIMARY KEY (`Thang`, `Nam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EzHRM`.`CACHTINHLUONG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`CACHTINHLUONG` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`CACHTINHLUONG` (
  `Ten` ENUM('TheoGio', 'TheoThang') NOT NULL,
  `KyHanTraLuongTheoNgay` INT NULL,
  `LanTraLuongCuoi` DATE NOT NULL DEFAULT (CURRENT_DATE),
  `NgayTinhLuongThangNay` DATE NULL,
  PRIMARY KEY (`Ten`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EzHRM`.`CACLOAIVIPHAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`CACLOAIVIPHAM` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`CACLOAIVIPHAM` (
  `TenViPham` VARCHAR(255) NOT NULL,
  `TruLuongTheoPhanTram` FLOAT NOT NULL,
  `TruLuongTrucTiep` DECIMAL NOT NULL,
  PRIMARY KEY (`TenViPham`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EzHRM`.`CHAMCONG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`CHAMCONG` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`CHAMCONG` (
  `ThoiGianVaoLam` DATETIME NOT NULL,
  `IDNhanVien` VARCHAR(10) NOT NULL,
  `ThoiGianTanLam` DATETIME NULL,
  PRIMARY KEY (`ThoiGianVaoLam`, `IDNhanVien`),
  CONSTRAINT `FK_CHAMCONG_IDNHANVIEN_ID`
    FOREIGN KEY (`IDNhanVien`)
    REFERENCES `EzHRM`.`NHANVIEN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_CHAMCONG_IDNHANVIEN_ID_idx` ON `EzHRM`.`CHAMCONG` (`IDNhanVien` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `EzHRM`.`CHUCVU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`CHUCVU` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`CHUCVU` (
  `TenChucVu` VARCHAR(255) NOT NULL,
  `CachTinhLuong` ENUM('TheoGio', 'TheoThang') NOT NULL,
  `TienLuongMoiGio` DECIMAL NOT NULL,
  `TienLuongMoiThang` DECIMAL NOT NULL,
  `PhanTramLuongNgoaiGio` FLOAT NOT NULL,
  `DaXoa` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`TenChucVu`),
  CONSTRAINT `FK_CHUCVU_CACHTINHLUONG_TEN`
    FOREIGN KEY (`CachTinhLuong`)
    REFERENCES `EzHRM`.`CACHTINHLUONG` (`Ten`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_CHUCVU_CACHTINHLUONG_TEN_idx` ON `EzHRM`.`CHUCVU` (`CachTinhLuong` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `EzHRM`.`EVENTLOG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`EVENTLOG` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`EVENTLOG` (
  `LogTime` VARCHAR(255) NOT NULL,
  `Message` VARCHAR(255) NOT NULL,
  `HomQua` DATE NULL,
  `GioVaoLamHomQua` DATETIME NULL,
  `GioTanLamHomQua` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EzHRM`.`LUONG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`LUONG` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`LUONG` (
  `NgayTinhLuong` DATE NOT NULL,
  `IDNhanVien` VARCHAR(10) NOT NULL,
  `TienLuong` DECIMAL NOT NULL,
  `TienTruLuong` DECIMAL NOT NULL,
  `TienThuong` DECIMAL NOT NULL,
  `TongTienLuong` DECIMAL NOT NULL,
  PRIMARY KEY (`NgayTinhLuong`, `IDNhanVien`),
  CONSTRAINT `FK_LUONG_IDNHANVIEN_ID`
    FOREIGN KEY (`IDNhanVien`)
    REFERENCES `EzHRM`.`NHANVIEN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_LUONG_IDNHANVIEN_ID_idx` ON `EzHRM`.`LUONG` (`IDNhanVien` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `EzHRM`.`NGHILE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`NGHILE` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`NGHILE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Ngay` TINYINT NOT NULL,
  `Thang` TINYINT NOT NULL,
  `SoNgayNghi` TINYINT NOT NULL,
  `TenDipNghiLe` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EzHRM`.`NGHIPHEP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`NGHIPHEP` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`NGHIPHEP` (
  `IDNhanVien` VARCHAR(10) NOT NULL,
  `NgayBatDauNghi` DATE NOT NULL,
  `SoNgayNghi` INT NOT NULL,
  `LyDoNghi` MEDIUMTEXT NOT NULL,
  `CoPhep` TINYINT NOT NULL,
  PRIMARY KEY (`IDNhanVien`, `NgayBatDauNghi`),
  CONSTRAINT `FK_NGHIPHEP_IDNHANVIEN_ID`
    FOREIGN KEY (`IDNhanVien`)
    REFERENCES `EzHRM`.`NHANVIEN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EzHRM`.`NHANVIEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`NHANVIEN` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`NHANVIEN` (
  `ID` VARCHAR(10) NOT NULL,
  `Ho` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `Ten` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `CMND` VARCHAR(45) NOT NULL,
  `NgaySinh` DATE NOT NULL,
  `EmailVanPhong` VARCHAR(45) NOT NULL,
  `EmailCaNhan` VARCHAR(45) NOT NULL,
  `SDTVanPhong` VARCHAR(45) NOT NULL,
  `SDTCaNhan` VARCHAR(45) NOT NULL,
  `NgayVaoLam` DATE NOT NULL,
  `NgayThoiViec` DATE NULL DEFAULT NULL,
  `PhongBan` VARCHAR(255) NOT NULL,
  `ChucVu` VARCHAR(255) NOT NULL,
  `TaiKhoan` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_NHANVIEN_TAIKHOAN_TAIKHOAN`
    FOREIGN KEY (`TaiKhoan`)
    REFERENCES `EzHRM`.`TAIKHOAN` (`TaiKhoan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_NHANVIEN_PHONGBAN_PHONGBAN`
    FOREIGN KEY (`PhongBan`)
    REFERENCES `EzHRM`.`PHONGBAN` (`TenPhong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_NHANVIEN_CHUCVU_CHUCVU`
    FOREIGN KEY (`ChucVu`)
    REFERENCES `EzHRM`.`CHUCVU` (`TenChucVu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_NHANVIEN_TAIKHOAN_TAIKHOAN_idx` ON `EzHRM`.`NHANVIEN` (`TaiKhoan` ASC) VISIBLE;

CREATE INDEX `FK_NHANVIEN_PHONGBAN_PHONGBAN_idx` ON `EzHRM`.`NHANVIEN` (`PhongBan` ASC) VISIBLE;

CREATE INDEX `FK_NHANVIEN_CHUCVU_CHUCVU_idx` ON `EzHRM`.`NHANVIEN` (`ChucVu` ASC) VISIBLE;

CREATE UNIQUE INDEX `TaiKhoan_UNIQUE` ON `EzHRM`.`NHANVIEN` (`TaiKhoan` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `EzHRM`.`NHOMTAIKHOAN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`NHOMTAIKHOAN` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`NHOMTAIKHOAN` (
  `TenNhomTaiKHoan` VARCHAR(255) NOT NULL,
  `QuyenHan` INT NOT NULL,
  PRIMARY KEY (`TenNhomTaiKHoan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EzHRM`.`PHONGBAN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`PHONGBAN` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`PHONGBAN` (
  `TenPhong` VARCHAR(255) NOT NULL,
  `NgayThanhLap` DATE NOT NULL DEFAULT (CURRENT_DATE),
  `NgayNgungHoatDong` DATE NULL DEFAULT NULL,
  `TruongPhong` VARCHAR(10) NULL,
  PRIMARY KEY (`TenPhong`),
  CONSTRAINT `FK_PHONGBAN_TRUONGPHONG_ID`
    FOREIGN KEY (`TruongPhong`)
    REFERENCES `EzHRM`.`NHANVIEN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_PHONGBAN_TRUONGPHONG_ID_idx` ON `EzHRM`.`PHONGBAN` (`TruongPhong` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `EzHRM`.`PROFILEPICTURE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`PROFILEPICTURE` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`PROFILEPICTURE` (
  `ID` VARCHAR(10) NOT NULL,
  `Image` BLOB NOT NULL,
  `Width` INT NOT NULL,
  `Type` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `EzHRM`.`PROFILEPICTURE` (`ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `EzHRM`.`SOGIOLAMTRONGNGAY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`SOGIOLAMTRONGNGAY` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`SOGIOLAMTRONGNGAY` (
  `Ngay` DATE NOT NULL,
  `IDNhanVien` VARCHAR(10) NOT NULL,
  `SoGioLamTrongGio` INT NOT NULL DEFAULT 0,
  `SoGioLamNgoaiGio` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Ngay`, `IDNhanVien`),
  CONSTRAINT `FK_DONVICONGVIEC_IDNHANVIEN_ID`
    FOREIGN KEY (`IDNhanVien`)
    REFERENCES `EzHRM`.`NHANVIEN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `ID_idx` ON `EzHRM`.`SOGIOLAMTRONGNGAY` (`IDNhanVien` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `EzHRM`.`TAIKHOAN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`TAIKHOAN` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`TAIKHOAN` (
  `TaiKhoan` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(64) NOT NULL,
  `NhomTaiKhoan` VARCHAR(255) NOT NULL,
  `DangLogin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`TaiKhoan`),
  CONSTRAINT `FK_NHOMTAIKHOAN_NHOMTAIKHOAN_TENNHOM`
    FOREIGN KEY (`NhomTaiKhoan`)
    REFERENCES `EzHRM`.`NHOMTAIKHOAN` (`TenNhomTaiKHoan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_NHOMTAIKHOAN_NHOMTAIKHOAN_TENNHOM_idx` ON `EzHRM`.`TAIKHOAN` (`NhomTaiKhoan` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `EzHRM`.`THAMSO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`THAMSO` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`THAMSO` (
  `ThoiDiemTao` DATETIME NOT NULL,
  `CoLamThuHai` TINYINT NOT NULL,
  `CoLamThuBa` TINYINT NOT NULL,
  `CoLamThuTu` TINYINT NOT NULL,
  `CoLamThuNam` TINYINT NOT NULL,
  `CoLamThuSau` TINYINT NOT NULL,
  `CoLamThuBay` TINYINT NOT NULL,
  `CoLamChuNhat` TINYINT NOT NULL,
  `ThoiGianChoPhepDiTre` TIME NOT NULL COMMENT 'In minutes cause store this in time would be weird',
  `ThoiGianChoPhepVeSom` TIME NOT NULL COMMENT 'In minutes',
  `ThoiGianDiTreToiDa` TIME NOT NULL,
  `ThoiGianVeSomToiDa` TIME NOT NULL,
  PRIMARY KEY (`ThoiDiemTao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EzHRM`.`THOIGIANBIEUTUAN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`THOIGIANBIEUTUAN` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`THOIGIANBIEUTUAN` (
  `ThoiDiemTao` DATETIME NOT NULL,
  `GioVaoLamCacNgayTrongTuan` TIME NOT NULL,
  `GioVaoLamThuBay` TIME NOT NULL,
  `GioVaoLamChuNhat` TIME NOT NULL,
  `GioTanLamCacNgayTrongTuan` TIME NOT NULL,
  `GioTanLamThuBay` TIME NOT NULL,
  `GioTanLamChuNhat` TIME NOT NULL,
  PRIMARY KEY (`ThoiDiemTao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EzHRM`.`TRULUONG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EzHRM`.`TRULUONG` ;

CREATE TABLE IF NOT EXISTS `EzHRM`.`TRULUONG` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Ngay` DATE NOT NULL,
  `IDNhanVien` VARCHAR(10) NOT NULL,
  `TenViPham` VARCHAR(255) NOT NULL,
  `SoTienTru` DECIMAL NOT NULL,
  `SoPhanTramTru` FLOAT NOT NULL,
  `GhiChu` TEXT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_TRULUONG_IDNHANVIEN_ID`
    FOREIGN KEY (`IDNhanVien`)
    REFERENCES `EzHRM`.`NHANVIEN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TRULUONG_TENVIPHAM`
    FOREIGN KEY (`TenViPham`)
    REFERENCES `EzHRM`.`CACLOAIVIPHAM` (`TenViPham`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_TRULUONG_IDNHANVIEN_ID_idx` ON `EzHRM`.`TRULUONG` (`IDNhanVien` ASC) VISIBLE;

CREATE INDEX `FK_TRULUONG_TENVIPHAM_idx` ON `EzHRM`.`TRULUONG` (`TenViPham` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
